feat: navbar in every page as navigation method
b1tsway/b1tsway.github.io pull request #10
Opened 2023-08-09 13:59 UTC by assebc

![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/6dc102c0-eda3-4616-8ae7-b7ca6fff4b41)

## Issue
https://github.com/b1tsway/b1tsway.github.io/issues/9

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I tested all related functionalities and I didn´t break anything

2023-08-09 15:26 UTC, Mariii-23 commented
In other sizes don't work
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/add5a873-a994-4d1a-9691-f28d49a10623)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/7f682b7b-dcf3-4487-9f39-18b836951a67)

2023-08-09 15:26 UTC, Mariii-23 requested changes
Fix the layout pls

2023-08-10 22:06 UTC, assebc commented
when in mobile version hides the two sections in navbar

2023-08-11 08:35 UTC, Mariii-23 requested changes
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/49f52a58-ce21-43ab-a453-b86dcba187bb)
:eyes:

2023-08-11 08:35 UTC, Mariii-23 commented on src/pages/Home/index.tsx
> +            <Header style={{height: "90vh"}}/>
I don't know to what extent in this case to define that the ``min-height`` is "90vh" in the component itself than to be outside.

I don't know if it's correct that we are allowing to pass the style in the component.

2023-08-12 09:17 UTC, assebc commented on src/pages/Home/index.tsx
> +            <Header style={{height: "90vh"}}/>
this is from a previous PR that was already merged

2023-08-12 09:17 UTC, assebc commented on src/pages/Home/index.tsx
> +            <Header style={{height: "90vh"}}/>
either way why not? it is a props as everything else?

2023-08-12 11:00 UTC, Mariii-23 approved these changes

2023-08-12 12:30 UTC, merged