first version of sections in about us page
b1tsway/b1tsway.github.io pull request #13
Opened 2023-08-09 16:01 UTC by assebc

![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/45b6644b-cc63-4d33-9dc5-d8b815148f8b)

## Issue
https://github.com/b1tsway/b1tsway.github.io/issues/6

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [] I tested all related functionalities and I didn´t break anything

2023-08-09 16:33 UTC, Mariii-23 requested changes
LGTM  but in some sizes it looks strange.

Here we can decrease margin
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/16d46aef-14da-48c7-8a71-79b6a7ad1de4)

In small sizes we can change to vertical
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/be760138-5d2f-48de-a4ac-0af1fd59df28)

2023-08-11 08:47 UTC, Mariii-23 requested changes

2023-08-11 08:47 UTC, Mariii-23 commented on src/pages/Home/styles.css
> +        width: 50%;
I think it's preferable to use the grid to make the 2 columns, because in some sizes the 1 column should have less than 50%
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/78474bb3-65d1-4014-b016-aeace99ae88d)

Probably changing the 50% to small screens solves the tele problem too
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/bbd1482f-eb0d-4e37-96aa-77fdc15de91d)

2023-08-11 08:47 UTC, Mariii-23 commented on src/components/atoms/Section/index.tsx
> +    style?: CSSProperties | undefined;
This prop isn't being used, and I don't know if it's good practice to have it.

2023-08-12 09:09 UTC, assebc commented on src/components/atoms/Section/index.tsx
> +    style?: CSSProperties | undefined;
of course it is being used, look down in the file

2023-08-12 14:55 UTC, assebc commented on src/pages/Home/styles.css
> +        width: 50%;
i used flex in a way to balance things instead to use columns but see what you think

2023-08-13 14:09 UTC, Mariii-23 approved these changes

2023-08-13 14:09 UTC, Mariii-23 commented on src/pages/Home/styles.css
> +    }
Would be better if this ``css`` belong to the component ``section``, so if we used it again it always look the same.

2023-08-13 14:30 UTC, merged