W-7
b1tsway/b1tsway.github.io pull request #38
Opened 2023-08-21 13:25 UTC by assebc

# Description

![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/0f2f10ae-d697-45f5-b74f-9cea2a02f700)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/effc0793-023b-47cb-977b-ddeaf01e70ff)

## Issue
https://github.com/b1tsway/b1tsway.github.io/issues/7

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I tested all related functionalities and I didn´t break anything

2023-08-21 20:04 UTC, Mariii-23 requested changes
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/b1d66755-ff06-4228-9826-4a00377ae0f3)
Can we try for images instead of text?

2023-08-21 20:04 UTC, Mariii-23 commented on src/components/atoms/ServiceCard/index.tsx
This is not an ``atom``, change this to ``molecule``

2023-08-21 20:04 UTC, Mariii-23 commented on src/components/organisms/Services/configs.ts
This should be a ```json``` file.

2023-08-22 10:00 UTC, assebc commented
> ![image](https://user-images.githubusercontent.com/61967105/262141502-b1d66755-ff06-4228-9826-4a00377ae0f3.png) Can we try for images instead of text?

how so? any design example?

2023-08-22 10:08 UTC, Mariii-23 commented
> 

like:
figma:



> > ![image](https://user-images.githubusercontent.com/61967105/262141502-b1d66755-ff06-4228-9826-4a00377ae0f3.png) Can we try for images instead of text?
> 
> how so? any design example?

Something like that:

- figma
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/7c2e2994-82a8-4008-8e0e-2f3f0dd48c26)
- photoshop
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/057e2262-db8a-4eaf-a18d-9c0e889d1ecc)
- ilustrator
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/b45182c5-bcb0-44b7-8487-91340ecb89fb)

- premiere
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/1f8f460f-fc96-44d1-abd2-1a46b7180151)

2023-08-22 10:44 UTC, assebc commented on src/components/organisms/Services/configs.ts
using json I cant use interface I define or can I?

2023-08-22 10:47 UTC, assebc commented on src/components/organisms/Services/configs.ts
let this pass without json so I can use dirs from main without need to merge

2023-08-22 11:22 UTC, assebc commented
![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/15f6bc33-2013-4cfb-8011-9414a20d3da9)

2023-08-22 13:31 UTC, Mariii-23 requested changes

2023-08-22 13:31 UTC, Mariii-23 commented on src/components/molecules/ServiceCard/index.tsx
> +        <div className="card-wrapper">
Pls change this to ``service-card-wrapper``,  if we always use the same name for the classname it will start to collide with other components (it already happened)

2023-08-22 13:31 UTC, Mariii-23 commented on src/components/molecules/ServiceCard/styles.css
> +    margin: 10px 0;
/4

2023-08-22 13:38 UTC, Mariii-23 approved these changes

2023-08-23 09:12 UTC, merged