W-52 Add Services page
b1tsway/b1tsway.github.io pull request #63
Opened 2023-08-29 10:39 UTC by Mariii-23

# Description
The main goal of this pr is to add a ``Service`` page.

![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/133b4f7d-61d8-4b47-9177-ac765a554895)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/dbdd5a04-cfd3-48e3-b7b2-e0c424c35c5f)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/4894e15d-072e-477e-bb0d-194463b00820)
On mobile:
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/f23c5f0e-9b4f-4ed4-acb5-cc288ce8aa16)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/732a77e3-8e05-4a13-ac30-c3016dea9254)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/7134413e-b4cb-4c96-a76d-4fa8f13474af)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/07ad8959-1d8e-44d8-b193-ebd542041908)

Here we also add:

- ``ServiceHero`` component
here we can change the image
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/6eb67b2f-735b-49c2-ab9b-caa99840c2ee)

- ``BringVisionToLife`` component
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/228d72b6-454a-42d4-87fc-8a99e9ee1c0e)

- ``AdvantageCards`` and ``AdvantageCard`` component
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/1be2c119-e789-4aa3-ba41-e3e96d1c65e6)

- ``SimpleServiceCards`` and ``SimpleServiceCard`` component
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/1d3aacc9-6d8c-4d7f-a802-39f10323f3aa)

## Issue
https://github.com/b1tsway/b1tsway.github.io/issues/52

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I tested all related functionalities and I didn´t break anything

2023-08-29 11:11 UTC, assebc commented on src/components/molecules/CallToAction/FindRightSolution/index.tsx
> +                <h2>We’ll help you find the right solution for your organization’s unique needs — customized software, website development, maintenance services</h2>
this text looks weird when deploy and dont forget the dot at the end

2023-08-29 11:15 UTC, assebc requested changes

2023-08-29 11:15 UTC, assebc commented on src/pages/Services/index.tsx
> +        </Layout.Body>
change this order

2023-08-29 11:15 UTC, assebc commented on src/components/molecules/CallToAction/FindRightSolution/index.tsx
> +                <h2>We’ll help you find the right solution for your organization’s unique needs — customized software, website development, maintenance services</h2>
this text looks weird when deploy and dont forget the dot at the end

![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/773b2244-f147-4f00-927d-e64127b636dc)

2023-08-29 11:15 UTC, assebc commented on src/components/molecules/Hero/ServicesHero/index.tsx
> +                <Cards.SimpleService services={servicesInfoData}/>
titles look weird when resized

![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/76c58ba6-3ee4-4d8f-849d-b1b5d198a4e0)

2023-08-30 09:52 UTC, Mariii-23 commented on src/components/molecules/CallToAction/FindRightSolution/index.tsx
> +                <h2>We’ll help you find the right solution for your organization’s unique needs — customized software, website development, maintenance services</h2>
The problem is fix.
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/4b460bb4-abb6-4787-a666-61d385b99f17)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/9b7a4415-c4ec-489c-9633-c3c9949d5e17)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/2e8d3ade-84b1-4894-8cbf-883da8eb32ae)

2023-08-30 10:03 UTC, Mariii-23 commented on src/components/molecules/Hero/ServicesHero/index.tsx
> +                <Cards.SimpleService services={servicesInfoData}/>
The problem is solved.
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/20ca8cac-7fea-449b-b9cc-191a27733f22)

2023-08-30 10:08 UTC, Mariii-23 commented on src/pages/Services/index.tsx
> +        </Layout.Body>
I prefer it as it is because the order in which the customer will see it will be:

- information about services
- benefits we provide
- tools we use to achieve this

and after this information you immediately have a call to action

if we put the call to action after the QA, I think it would cut the effect, and people who might even be tempted to send a message, wouldn't do.

What do you think?

2023-08-30 12:53 UTC, assebc approved these changes
lgtm!

2023-08-30 14:53 UTC, merged