feat: inserting imgs to hero
b1tsway/b1tsway.github.io pull request #64
Opened 2023-08-29 11:07 UTC by assebc

no prints please open and test

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I tested all related functionalities and I didn´t break anything

2023-08-29 21:01 UTC, Mariii-23 commented on src/components/molecules/Hero/ContactUsHero/styles.css
> +        height: 31%;
/4

2023-08-30 13:02 UTC, assebc commented on src/components/molecules/Hero/ContactUsHero/index.tsx
which whitespace?

2023-08-30 14:58 UTC, Mariii-23 requested changes
Resolve the conflicts pls

2023-08-30 17:16 UTC, Mariii-23 approved these changes
I think it's important that we leave some pages without the videos so we don't get so tired and get more impact. Pages like the contactUs and the services.

LGTM

2023-08-30 17:39 UTC, merged