Change contactUsHero
b1tsway/b1tsway.github.io pull request #68
Opened 2023-08-31 08:39 UTC by Mariii-23

# Description
The main goal of this pr is to change the ContactUsHero and the contact's page.
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/1c0086f4-fecd-4a28-8b72-4307b1317344)
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/1836822d-6215-4215-a1d5-fe70fef59313)

The size and colors of the font will be perfected in another PR.

## Issue

https://github.com/b1tsway/b1tsway.github.io/issues/65

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I tested all related functionalities and I didn´t break anything

2023-08-31 10:57 UTC, assebc requested changes

2023-08-31 10:57 UTC, assebc commented on src/components/molecules/Hero/ContactUsHero/index.tsx
> +            <h1 className="text-lines">Let's Talk!!!</h1>
dont like this effect

2023-08-31 10:57 UTC, assebc commented on src/components/molecules/Hero/ContactUsHero/styles.css
> +  bottom: -16px;
this effect

2023-08-31 10:57 UTC, assebc commented on src/pages/ContactUs/index.tsx
> +                        <p>Try to provide us with the most relevant information about you and your project.
"Enrich us about your projects and ideas"

2023-08-31 11:16 UTC, Mariii-23 commented on src/components/molecules/Hero/ContactUsHero/index.tsx
> +            <h1 className="text-lines">Let's Talk!!!</h1>
Fix. I remove the effect

2023-08-31 11:16 UTC, Mariii-23 commented on src/components/molecules/Hero/ContactUsHero/styles.css
> +  bottom: -16px;
what do you think know?

![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/908dd4d6-11bb-46ae-ad20-72a1e467b3d8)

2023-08-31 11:19 UTC, Mariii-23 commented on src/pages/ContactUs/index.tsx
> +                        <p>Try to provide us with the most relevant information about you and your project.
I like this:
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/a86ee444-bbfb-4c86-b45e-960eb245e99a)
What do you think?

2023-08-31 11:32 UTC, assebc requested changes
didnt like how it turns out im sorry!

try :

"Let us transform your vision into reality through our expert software development services."

as text before form

inside hero, remove let's talk and put the "enrich..." text

2023-08-31 13:32 UTC, Mariii-23 commented
> 
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/3ec2890c-4b04-4649-bba8-94947f0e8565)

2023-08-31 21:29 UTC, assebc requested changes

2023-08-31 21:29 UTC, assebc commented on src/components/molecules/Hero/ContactUsHero/index.tsx
> +        <h1>{"Enrich us about your projects and ideas"}</h1>
why this tipography have  different signatures but are the same, uniformize it!

2023-09-01 09:14 UTC, Mariii-23 commented on src/components/molecules/Hero/ContactUsHero/index.tsx
> +        <h1>{"Enrich us about your projects and ideas"}</h1>
Done

2023-09-01 09:14 UTC, assebc approved these changes
lgtm!

2023-09-01 09:15 UTC, merged