feat: form from contact-us page
b1tsway/b1tsway.github.io pull request #8
Opened 2023-08-09 13:06 UTC by assebc

![image](https://github.com/b1tsway/b1tsway.github.io/assets/73396142/2f0a16b5-7b6b-40ed-b194-c31a96b457ab)

## Issue
https://github.com/b1tsway/b1tsway.github.io/issues/2

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I tested all related functionalities and I didn´t break anything

2023-08-09 14:38 UTC, Mariii-23 requested changes

2023-08-09 14:38 UTC, Mariii-23 commented on src/pages/Contact/index.tsx
> +                        />
You can change this to type="tel" and add some verification.
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/e3cc6d16-b5f9-4c62-b3c5-7f17001c2529)
This is a example, don't put the phone number with the "-".

2023-08-09 14:38 UTC, Mariii-23 commented on src/pages/Contact/index.tsx
> +            </form>
You can create a organism with all of this form

2023-08-09 14:41 UTC, Mariii-23 requested changes

2023-08-09 14:41 UTC, Mariii-23 commented on src/pages/Contact/index.tsx
> +            formRef.current.message.value
you can do this adding a "required" prop on the inputs

2023-08-09 14:54 UTC, assebc commented on src/pages/Contact/index.tsx
> +                        />
how do you know where is the client from to define this?

2023-08-09 15:00 UTC, assebc commented on src/pages/Contact/index.tsx
> +            formRef.current.message.value
this is a way to find which response the emailjs api returns so we know, possible answers by using only required:

- 200
- 202
- 203
- 204
- 500

2023-08-09 15:25 UTC, Mariii-23 commented
Don't work in all sizes
![image](https://github.com/b1tsway/b1tsway.github.io/assets/61967105/97da181a-7bdd-4c12-b417-f64b400a15dc)

2023-08-11 08:18 UTC, Mariii-23 commented on src/components/organisms/Form/index.tsx
> +                        <Input type="text" name="name" autoComplete="new-password" />
Don't know if it's best to create a component called ``RequiredInput`` and do something like it exists in the menu project.
So we don't have as much repeated code

2023-08-11 08:18 UTC, Mariii-23 commented on src/components/organisms/Form/styles.css
> +        font-size: 18px;
We will need to put this on ``.root`` or in the ``Button`` component, so all buttons look like the same.

2023-08-11 08:18 UTC, Mariii-23 commented on src/components/organisms/Form/index.tsx
> +import { Button, Col, Input, Row, message } from "antd";
Is this really necessary, since we are adding a heavy dependency?
Maybe it would be preferable to create a ``button`` , ``notification``, ``Input`` components and use the ``col``, ``row`` of the html.

2023-08-13 14:03 UTC, Mariii-23 requested changes

2023-08-13 14:03 UTC, Mariii-23 commented on src/components/molecules/FormInput/index.tsx
> +    if (props.htmlFor === "message"){
You can create other component for the message because it's not a ``input``

2023-08-13 14:32 UTC, assebc commented on src/components/molecules/FormInput/index.tsx
> +    if (props.htmlFor === "message"){
text area isnt an input?

2023-08-13 14:35 UTC, Mariii-23 commented on src/components/molecules/FormInput/index.tsx
> +    if (props.htmlFor === "message"){
You are right

2023-08-13 15:23 UTC, Mariii-23 approved these changes

2023-08-13 15:29 UTC, merged